### ISSUE TITLE
500 error when getting attestation token

### ISSUE THREAD

**Issue by miller93** [mgp25/Snap-API#208]
I keep getting a 500 error response when posting to https://api.casper.io/droidguard/attest/binary it was working fine this morning is the server under maintenance or something?

**Comment by liamcottle** [comment]
Hi,

Yes this is an issue on my end.

Google continuously make changes to their internal systems, and it appears there's a bug in my internal code which makes the automatic system updating fail when Google releases new internal code.

I'm in the process of getting it sorted out, to avoid the server having any more downtime (eg 500 errors), however you'll all just have to be patient as this will take me some time.

I will eventually be setting up a system with API keys to use the Casper API, as it costs me quite a sum of money to have these servers running for you all.

Cheers.

**Comment by robertdo** [comment]
@liamcottle maybe you could put some of these pieces on github like you did with your attestation servlet? that way we can self host and not overload your servers.

**Comment by liamcottle** [comment]
Hi @robertdo,

Unfortunately I can not provide you with the source code behind the Casper API Attestation/DroidGuard system.

This is in my best interests, as well as the general public, as it uses private internal code from within the Google DroidGuard system, which they have gone to great lengths to prevent the public from obtaining.

I have spoken to one of Google's Security Software Engineering teams recently about the DroidGuard system, and it's best that the source code of my system is not readily available for looking at, as it will cause security issues for other systems available by Google.

I'm in the process of setting up a Client Portal where users of the Casper API can register for an API Key to use the Casper Attestation system, and other API's that come about in the future for accessing Snapchat.

I'll be providing more information about this, when the time arises.

However, for now, if you use my API's for obtaining Client Auth Tokens and Attestations, you'll have to be patient if the system isn't working at the time.

I do know it appears to stop working sometimes, and have found the root cause of this. I'm in the process of getting it sorted out.

Cheers,
Liam Cottle
