### ISSUE TITLE
Missing/new friend type

### ISSUE THREAD

**Issue by Chiggins** [mgp25/Snap-API#219]
So I'm looking through some friends and there seems to be a different type that I'm not exactly sure what it is. Currently we have the following:

``` php
    const FRIEND_CONFIRMED      = 0;
    const FRIEND_UNCONFIRMED    = 1;
    const FRIEND_BLOCKED        = 2;
    const FRIEND_DELETED        = 3;
```

Now I'm seeing that there's another type, which is 6. Not too sure what it is, was hoping for some clarification on that, and seeing if there can be a `const` added for that.

**Comment by liamcottle** [comment]
Heya, Looking into the decompiled code of the 9.16.2.0 Snapchat APK, this is what each value represents.

```
FRIEND(0),
PENDING(1),
BLOCKED(2),
DELETED(3),
INVITE_PLACEHOLDER(4),
LOCKED_PLACEHOLDER(5),
FOLLOWING(6),
UNRECOGNIZED_VALUE(-9999);
```

So in my opinion, `FOLLOWING(6)` would mean they have their story privacy set to `EVERYONE`, and you have added them as a friend, but they haven't added you back.

I'd believe, if the value is `PENDING(1)` instead of `FOLLOWING(6)`, then it would be the same situation, but the user has their stories set to `FRIENDS` only.

This is just what I would expect. I haven't done any testing around it.

**Comment by liamcottle** [comment]
Okay, did some research.

If you have your "Send me Snaps" Privacy set to Friends `snap_p=1`, the server will return the type `PENDING(1)` for that Friend Request.

If you have your "Send me Snaps" Privacy set to Everyone `snap_p=0` , the server will return the type `FOLLOWING(6)` for that Friend Request.

If you accept that Friend Request, it will change to `FRIEND(0)`

So:

``` php
const FRIEND_CONFIRMED      = 0;
const FRIEND_UNCONFIRMED    = 1;
const FRIEND_BLOCKED        = 2;
const FRIEND_DELETED        = 3;
const FRIEND_FOLLOWING      = 6;
```
