### ISSUE TITLE
caspert api snapchat issue for login

### ISSUE THREAD

**Issue by keyur23383** [mgp25/Snap-API#278]
Is there any update on this.? My project is totally depend on this please help me when it will solve?

**Comment by Snowlav** [comment]
Fucking read idiot.
Op 28 dec. 2015 07:26 schreef "keyur23383" notifications@github.com:

**Comment by mzahlag** [comment]
I have been reading for two months now didn't find any thing maybe i missed something but obviously all of you are repeating the same sentence read to all the users so i think 1- you have hidden the fix thing between lines because of the agreement between you and snap-hack 2- you want people to wait until you fix it. But you fixed it and using it and I paid for the service and i can't use it because you are too damn selfish  to share

**Comment by Snowlav** [comment]
You are funny my friend.
Op 28 dec. 2015 07:59 schreef "mzahlag" notifications@github.com:

> I have been reading for two months now didn't find any thing maybe i
> missed something but obviously all of you are repeating the same sentence
> read to all the users so i think 1- you have hidden the fix thing between
> lines because of the agreement between you and snap-hack 2- you want people
> to wait until you fix it. But you fixed it and using it and I paid for the
> service and i can't use it because you are too damn selfish to share
> 
> Sent from my iPhone
>

**Comment by teknogeek** [comment]
you want a fix faster? do it yourself.

**Comment by Snowlav** [comment]
You closed all the fun D:
Op 28 dec. 2015 08:04 schreef "Joel Margolis" notifications@github.com:

**Comment by mzahlag** [comment]
With this attitude don't excepting me to donate or to subscribe to the api you took my money for something worked for a week i will hire a freelancer to do it for me thank you for your time

**Comment by teknogeek** [comment]
I'm really curious what you think we do all day

**Comment by mzahlag** [comment]
Bro i know you are working hard but Casper, snaphack , Uploadnroll ect ect they fixed it if this project is working in casper andriod why it shouldn't work here if you need help i will share money and my co-worker will share his time developing with you

**Comment by liamcottle** [comment]
The reason Casper works, is because I am the developer of the Casper app.

Snap-Hack and UploadnRoll work, because the developers of those apps work directly with me.

The reason this library isn't working, is because it relied on old systems provided by my API which Google have patched, thus no longer work.

At this stage, I can not provide you all with access to my Private API for Snapchat logins, as it will cause major problems for myself, and the other developers I work with.

I may provide a Public API in the future, however at this stage I can not do so.

**Comment by Chiggins** [comment]
Word of advice, use Casper to login and then take the Auth tokens for use
with this library and others. As long as you have the Auth token, you're
golden.

**Comment by mzahlag** [comment]
@liamcottle im willing to pay to have private subscribe to use it , i don't have ios or andriod app i have my own software in my own pc to promote my sc account so there is no load on you so name your subscribe price and im happy to pay you can add me on skype @ mzahlag

**Comment by tttran1** [comment]
@liamcottle I'm also willing to pay to have access to your system.  Please skype me @ trung.tran2
