### ISSUE TITLE
send snap

### ISSUE THREAD

**Issue by ddaddy** [mgp25/Snap-API#6]
I'm just wondering why you are using the `/loq/retry` endpoint to sent a snap instead of the usual upload then send?

I'm getting a `500 error` trying to use `/loq/send so wondering` if that's why your not using it?

**Comment by mgp25** [comment]
@ddaddy because im using version 9 with this API, use the functions coded in the API. In version 9+ there are some dificulties with the normal endpoint so i just use that, once i organize the code ill start compliting all endpoints. But for now you can use this safely, and works 100%

Use `send` function with the endpoint `/loq/retry/`

And its a simple as doing this:

``` php
$path = "/Users/mgp25/Desktop/test.jpg";
$to = 'mgp25';

$snapchat->send($path, $to, 'holaa');
```

Regards
