### ISSUE TITLE
What happens in `http://tekno.pw/snapchat_password.php`

### ISSUE THREAD

**Issue by chrishutchinson** [mgp25/Snap-API#76]
This is less of an issue, more of a request for additional details - what actually happens in http://tekno.pw/snapchat_password.php to return the JSON object?

I'm concerned that these emails / passwords may get blocked by Snapchat, or might go down in the future. Is it possible to run my own version, and if so, can it be open sourced?

Thanks!

**Comment by MattieTK** [comment]
+1

**Comment by sallaben** [comment]
In the past he's said no for some reason. But hopefully we can get some
more details on what actually occurs here in this "issue".

**Comment by teknogeek** [comment]
It uses one of many random email and password pairs that are set by me and
@mgp25 and encrypts them with google password encryption code I cracked.
then it returns the email and the encryptedpasswd generated for it as JSON
for the API to use. I will not be open sourcing this code in order to stop
people from hacking the accounts we use

**Comment by md726** [comment]
Is it maybe possible to include an option directly in the code to provide username/password by my own instead of using the external php? Currently I'm replacing EncryptedPasswd by Passwd, $loginArray["email"], by my static mail and $loginArray["encryptedPassword"] by my static password. 

I'm doing it since I never got a successfull login when using the external php, but when using my own credentials it's always working. 

What I'm talking about... Currently when there is a new update provided by you I'm downloading the ZIP archive, replacing my files, but I have to edit the file always to change it from using the external php to my static credentials. So it would be really nice to include it directly in the class as an optional setting for using my personal credentials instead of calling the external URL and getting the external JSON (so there is no need to edit the snapchat.php manually after updating it).

**Comment by MattieTK** [comment]
Isn't this an extreme point of weakness for the api?

Could Snapchat not block all accounts authorised with this technique by scraping from your file? Would it not be more secure to allow people to create their own user:password keypairs using your hashing system.

How would a user be able to hack your accounts with just the script that generates the encrypted strings?

**Comment by teknogeek** [comment]
Yes I was about to say that. You can use your own email and password by calling `https://tekno.pw/snapchat_password.php?email=youremail@here.com&password=yourpasswordhere`

**Comment by MattieTK** [comment]
We're supposed to pass a totally unencrypted password to your script to use it?

Sounds like this is a bit of a two-tier system. How are we supposed to trust you to not hack **our** accounts?

This still doesn't eliminate the point of weakness also. Snapchat could spam requests to this script in order to bring everyone using this API down.

**Comment by teknogeek** [comment]
how would snapchat even know with this exists, and why would they DoS their own service
when i can encrypt and obfuscate the code enough to release it, i will

**Comment by teknogeek** [comment]
when i can encrypt and obfuscate the code enough to release it, i will

**Comment by md726** [comment]
@MattieTK 

Maybe this is a solution for you? https://github.com/mgp25/Snap-API/issues/42#issuecomment-87467213

**Comment by MattieTK** [comment]
Thanks @mands72 - I'll try that out but it looks promising

**Comment by teknogeek** [comment]
Yes that's been around for a long time

we used it for a few hours but the account got hacked in literally 2 hours, hence why we use this method now

**Comment by teknogeek** [comment]
we used it for a few hours but the account got hacked in literally 2 hours, hence why we use this method now

**Comment by md726** [comment]
I'm using it since about 2 weeks with my personal gmail account without any issues.

**Comment by teknogeek** [comment]
this also lets us push new accounts for anyone to use without having to make new commits
that's because you are using 1 account, from 1 IP, from 1 country

this is many accounts and login from many IPs from many countries

**Comment by teknogeek** [comment]
that's because you are using 1 account, from 1 IP, from 1 country

**Comment by teknogeek** [comment]
this is many accounts and login from many IPs from many countries

**Comment by md726** [comment]
Yes I completely agree with you and your solution and I'm thankful you did it! But in my case only that's working and that's why I asked to include a setting for providing mail/passwd manually instead of calling the url. Actually I have always to edit the snapchat.php for changing it to my own credentials

**Comment by mgp25** [comment]
We'll release `http://tekno.pw/snapchat_password.php` soon, im also adding a function so you can easily add your google account to use GAuth.

Regards

**Comment by md726** [comment]
Great! :-)

**Comment by MattieTK** [comment]
That's great to hear @mgp25, thanks very much.

**Comment by mgp25** [comment]
We arent going to use that server anymore. Now you have to provide your own data.

Commit: https://github.com/mgp25/Snap-API/commit/196ace3d87a7e356484583e0301ffbbbbf628e18

https://github.com/mgp25/Snap-API/wiki/Snap-API-Documentation#logging-in

Regards
